server:
  port: 8089

spring:
  hikari:
    connection-init-sql: SET NAMES utf8mb4
  datasource:
    url: jdbc:mysql://localhost:3306/rvblog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: Rv_Jiang
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql:
  #redis Config
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: qweasd
    timeout: 5000
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1  #连接池最大阻塞等待时间
        max-idle: 8   #连接池最大空闲时间
        min-idle: 0   #连接池最小连接时间
  servlet:
    multipart:
      max-file-size: 10485760 #10MB
      max-request-size: 104857600 #100MB


#MybatisPlus Config
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: rv_

#MyVariable
image:
  baseUrl: D:/RvBlogImages/
  requestUrl: http://localhost:8089/image/
  uploadImageSize: 10